name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Print versions
        run: deno --version

      - name: Format (check)
        run: deno task fmt:check

      - name: Lint
        run: deno task lint

      - name: Type check
        run: deno task check

      - name: Test
        run: deno task test
